
/**
 * @file attribs.h
 *
 * Defines the AttribUnion and attrib structures.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: attribs.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_ATTRIBS_H_
#define _SAC_ATTRIBS_H_

#include "types.h"


/******************************************************************************
 * For each node a structure of its attributes is defined, named 
 * ATTRIBS_<nodename>
 *****************************************************************************/
struct ATTRIBS_N_ARREXPR
{
};
struct ATTRIBS_N_ASSIGN
{
};
struct ATTRIBS_N_BINOP
{
  binop Op;
};
struct ATTRIBS_N_BOOL
{
  bool Value;
};
struct ATTRIBS_N_CAST
{
  type Type;
};
struct ATTRIBS_N_DECLS
{
};
struct ATTRIBS_N_DOWHILE
{
};
struct ATTRIBS_N_ERROR
{
  char *message;
  compiler_phase_t anyphase;
};
struct ATTRIBS_N_EXPRSTMT
{
};
struct ATTRIBS_N_EXPRS
{
};
struct ATTRIBS_N_FLOAT
{
  float Value;
};
struct ATTRIBS_N_FOR
{
  char *LoopVar;
};
struct ATTRIBS_N_FUNBODY
{
};
struct ATTRIBS_N_FUNCALL
{
  char *Name;
  node *Decl;
};
struct ATTRIBS_N_FUNDEF
{
  type Type;
  char *Name;
  struct
  {
    unsigned int IsExport:1;
  } flags;
};
struct ATTRIBS_N_FUNDEFS
{
};
struct ATTRIBS_N_GLOBDECL
{
  type Type;
  char *Name;
};
struct ATTRIBS_N_GLOBDEF
{
  type Type;
  char *Name;
  struct
  {
    unsigned int IsExport:1;
  } flags;
};
struct ATTRIBS_N_IDS
{
  char *Name;
};
struct ATTRIBS_N_IFELSE
{
};
struct ATTRIBS_N_MONOP
{
  monop Op;
};
struct ATTRIBS_N_NUM
{
  int Value;
};
struct ATTRIBS_N_PARAM
{
  char *Name;
  type Type;
};
struct ATTRIBS_N_PROGRAM
{
  node *SymbolTable;
};
struct ATTRIBS_N_RETURN
{
};
struct ATTRIBS_N_STMTS
{
};
struct ATTRIBS_N_SYMBOLTABLE
{
  node *Parent;
  int Distance;
};
struct ATTRIBS_N_SYMBOLTABLEENTRY
{
  char *Name;
  type Type;
  int Offset;
  int Params;
};
struct ATTRIBS_N_TERNARY
{
};
struct ATTRIBS_N_VAR
{
  char *Name;
  node *Decl;
};
struct ATTRIBS_N_VARDECL
{
  char *Name;
  type Type;
};
struct ATTRIBS_N_VARLET
{
  char *Name;
  node *Decl;
};
struct ATTRIBS_N_WHILE
{
};
/*****************************************************************************
 * This union handles all different types of attributes. Its members are
 * called N_nodename.
 ****************************************************************************/
struct ATTRIBUNION
{
  struct ATTRIBS_N_ARREXPR *N_arrexpr;
  struct ATTRIBS_N_ASSIGN *N_assign;
  struct ATTRIBS_N_BINOP *N_binop;
  struct ATTRIBS_N_BOOL *N_bool;
  struct ATTRIBS_N_CAST *N_cast;
  struct ATTRIBS_N_DECLS *N_decls;
  struct ATTRIBS_N_DOWHILE *N_dowhile;
  struct ATTRIBS_N_ERROR *N_error;
  struct ATTRIBS_N_EXPRSTMT *N_exprstmt;
  struct ATTRIBS_N_EXPRS *N_exprs;
  struct ATTRIBS_N_FLOAT *N_float;
  struct ATTRIBS_N_FOR *N_for;
  struct ATTRIBS_N_FUNBODY *N_funbody;
  struct ATTRIBS_N_FUNCALL *N_funcall;
  struct ATTRIBS_N_FUNDEF *N_fundef;
  struct ATTRIBS_N_FUNDEFS *N_fundefs;
  struct ATTRIBS_N_GLOBDECL *N_globdecl;
  struct ATTRIBS_N_GLOBDEF *N_globdef;
  struct ATTRIBS_N_IDS *N_ids;
  struct ATTRIBS_N_IFELSE *N_ifelse;
  struct ATTRIBS_N_MONOP *N_monop;
  struct ATTRIBS_N_NUM *N_num;
  struct ATTRIBS_N_PARAM *N_param;
  struct ATTRIBS_N_PROGRAM *N_program;
  struct ATTRIBS_N_RETURN *N_return;
  struct ATTRIBS_N_STMTS *N_stmts;
  struct ATTRIBS_N_SYMBOLTABLE *N_symboltable;
  struct ATTRIBS_N_SYMBOLTABLEENTRY *N_symboltableentry;
  struct ATTRIBS_N_TERNARY *N_ternary;
  struct ATTRIBS_N_VAR *N_var;
  struct ATTRIBS_N_VARDECL *N_vardecl;
  struct ATTRIBS_N_VARLET *N_varlet;
  struct ATTRIBS_N_WHILE *N_while;
};
#endif /* _SAC_ATTRIBS_H_ */
