
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 33
typedef enum
{ N_undefined = 0, N_program = 1, N_symboltable = 2, N_symboltableentry =
    3, N_decls = 4, N_exprs = 5, N_arrexpr = 6, N_ids = 7, N_exprstmt =
    8, N_return = 9, N_funcall = 10, N_cast = 11, N_fundefs = 12, N_fundef =
    13, N_funbody = 14, N_ifelse = 15, N_ternary = 16, N_while =
    17, N_dowhile = 18, N_for = 19, N_globdecl = 20, N_globdef = 21, N_param =
    22, N_vardecl = 23, N_stmts = 24, N_assign = 25, N_binop = 26, N_monop =
    27, N_varlet = 28, N_var = 29, N_num = 30, N_float = 31, N_bool =
    32, N_error = 33 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
