
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 10
typedef enum
{ N_undefined = 0, N_stmts = 1, N_assign = 2, N_binop = 3, N_varlet =
    4, N_var = 5, N_num = 6, N_float = 7, N_bool = 8, N_symboltableentry =
    9, N_error = 10 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
